language: r
cache: packages
latex: false
dist: trusty
sudo: required
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository ppa:opencpu/jq --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libv8-dev
  - sudo apt-get install --yes libjq-dev libprotobuf-dev libprotoc-dev protobuf-compiler

install:
  - cp fonts/ -r /usr/local/share/fonts
  - fc-cache -f -v
  - R -e "install.packages('devtools')"
  - R -e "install.packages('bookdown')"
  - R -e "install.packages('microbenchmark')"
  - R -e "install.packages('tinytex')"
  - R -e "tinytex::install_tinytex()"
  - R -e "devtools::install_github('nowosad/PSMpkg')"

script:
  - make all

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
